version: '3.8'

services:
  password-vault:
    build: .
    image: password-vault:latest
    container_name: password-vault
    ports:
      - "5002:5002"
    environment:
      VAULT_USER: ${VAULT_USER:-admin}
      VAULT_PASS: ${VAULT_PASS:-password}
      VAULT_SECRET: ${VAULT_SECRET:-change-me}
    volumes:
      # Persist the SQLite DB on the host so entries survive restarts
      - ./data/vault.db:/app/vault.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys; urllib.request.urlopen('http://127.0.0.1:5002')\" || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
